name: VictoriaMetrics UI
version: "1.29.22"
slug: vmetrics_ui
description: Database-style web interface for exploring VictoriaMetrics data
arch:
  - amd64
  - aarch64
init: true
homeassistant: "2024.1.0"
map:
  - config:ro
ingress: true
ingress_port: 3000
panel_icon: mdi:database-search
panel_title: VictoriaMetrics UI
image: ghcr.io/nksoft/vmetrics_ui
options:
  vm_url: "http://homeassistant:8428"
  vm_username: ""
  vm_password: ""
  log_level: "info"
schema:
  vm_url: str
  vm_username: str
  vm_password: str
  log_level: str
